services:
  memg-mcp-server:
    build:
      context: ..
      dockerfile: mcp/Dockerfile
      args:
        MEMG_YAML_SCHEMA: ${MEMG_YAML_SCHEMA:-config/software_dev.yaml}
    container_name: memg-mcp-server-${MEMORY_SYSTEM_MCP_PORT:-8787}
    ports:
      - "${MEMORY_SYSTEM_MCP_PORT:-8787}:${MEMORY_SYSTEM_MCP_PORT:-8787}"
    volumes:
      - ${BASE_MEMORY_PATH:-$HOME/.local/share/memory_system}_${MEMORY_SYSTEM_MCP_PORT:-8787}/qdrant:/qdrant
      - ${BASE_MEMORY_PATH:-$HOME/.local/share/memory_system}_${MEMORY_SYSTEM_MCP_PORT:-8787}/kuzu:/kuzu
    env_file:
      - .env
    environment:
      QDRANT_STORAGE_PATH: /qdrant
      KUZU_DB_PATH: /kuzu/memory_db
      MEMORY_SYSTEM_MCP_PORT: ${MEMORY_SYSTEM_MCP_PORT:-8787}
      MEMORY_SYSTEM_MCP_HOST: "0.0.0.0"  # Docker container binding
      MEMG_YAML_SCHEMA: ${MEMG_YAML_SCHEMA:-config/software_dev.yaml}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MEMORY_SYSTEM_MCP_PORT:-8787}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
