version: v1

id_policy:
  kind: uuid
  field: id

defaults:
  vector:
    metric: cosine
    normalize: true
  timestamps:
    auto_create: true
    auto_update: true

entities:
  - name: memo
    description: "Base memory unit"
    anchor: statement
    fields:
      id:          { type: string, required: true, system: true }
      user_id:     { type: string, required: true, system: true }
      statement:   { type: string, required: true, max_length: 8000 }
      created_at:  { type: datetime, required: true, system: true }
      updated_at:  { type: datetime, system: true }
      vector:      { type: vector, derived_from: statement, system: true }
    relations:
      - name: memo_related
        description: "Generic relation between memos"
        directed: true
        predicates: [RELATED_TO]
        source: memo
        target: memo

  - name: document
    parent: memo
    description: "Document-like memo with extended 'details' text"
    anchor: statement
    fields:
      details: { type: string, required: true }
    relations:
      - name: document_note
        description: "Document referenced by a note"
        directed: true
        predicates: [REFERENCED_BY]
        source: document
        target: note
      - name: task_document
        description: "Document providing details or requirements for a task"
        directed: true
        predicates: [SUPPORTS]
        source: document
        target: task

  - name: task
    parent: memo
    description: "Task-like memo"
    anchor: statement
    fields:
      details:   { type: string }
      status:    { type: enum, choices: [backlog, todo, in_progress, in_review, done, cancelled] }
      priority:  { type: enum, choices: [low, medium, high, critical] }
      assignee:  { type: string }
      due_date:  { type: datetime }
    relations:
      - name: task_note
        description: "Note associated with a task (comment or clarification)"
        directed: true
        predicates: [ANNOTATES]
        source: note
        target: task

  - name: note
    parent: memo
    description: "A simple note with a short 'details' field."
    anchor: statement
    fields:
      details: { type: string, required: true }
    relations:
      - name: note_document
        description: "Note providing additional context to a document"
        directed: true
        predicates: [ANNOTATES]
        source: note
        target: document
