version: v1

id_policy:
  kind: uuid
  field: id

defaults:
  vector:
    metric: cosine
    normalize: true
    dim: 384
  timestamps:
    auto_create: true
    auto_update: true

entities:
  - name: memo
    description: "Base memory unit"
    anchor: statement
    fields:
      id:          { type: string, required: true, system: true }
      user_id:     { type: string, required: true, system: true }
      statement:   { type: string, required: true, max_length: 8000 }
      tags:        { type: tags }
      confidence:  { type: float, default: 0.8, system: true }
      is_valid:    { type: bool, default: true, system: true }
      created_at:  { type: datetime, required: true, system: true }
      updated_at:  { type: datetime, system: true }
      vector:      { type: vector, dim: 384, derived_from: statement, system: true }

  - name: document
    parent: memo
    description: "Document-like memo with long body"
    anchor: statement
    fields:
      details:     { type: string, required: true }   # long text body

  - name: task
    parent: memo
    description: "Task-like memo"
    anchor: statement
    fields:
      details:     { type: string }                    # optional extra context
      status:      { type: enum, choices: [backlog, todo, in_progress, in_review, done, cancelled], default: todo }
      priority:    { type: enum, choices: [low, medium, high, critical], default: medium }
      assignee:    { type: string }
      due_date:    { type: datetime }

  - name: note
    parent: memo
    description: "A simple note."
    anchor: statement
    fields:
      details: { type: string, required: true }

relations:
  - name: memo_related
    description: "Generic relation between memos"
    directed: true
    predicates: [RELATED_TO]
    source: memo
    target: memo
