name: MEMG Core CI/CD Pipeline

on:
  push:
    branches: [ main, dev, dev-slim ]
  pull_request:
    branches: [ main, dev, dev-slim ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ##################### Security & Quality Checks ########################
  security-and-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ".[dev]"
          # Ensure Ruff is available for the next step
          pip install ruff

      - name: Security scan with bandit
        run: |
          echo "Running security scan with bandit..."
          bandit -r src/ -f json -o bandit-report.json || echo "Bandit found issues but continuing..."
          echo "Bandit report summary:"
          bandit -r src/

      - name: Code quality with ruff
        run: |
          echo "Running code quality checks with ruff..."
          ruff check src/ --output-format=json > ruff-report.json || echo "Ruff found issues"
          echo "Running ruff format check..."
          ruff format --check src/
          echo "Running ruff linting (will fail CI on issues)..."
          ruff check src/

      - name: Pylint code quality check
        run: |
          echo "Running pylint quality check..."
          pylint src/ --fail-under=7.0 --score=yes

      - name: Type checking with mypy
        run: |
          echo "Running type checking..."
          mypy src/ --ignore-missing-imports || echo "Type checking completed with warnings"

      - name: Run tests with coverage
        run: |
          echo "Running test suite with coverage (fail under 50% for lean core)..."
          pytest -vv \
            --cov=src/memory_system \
            --cov-report=term-missing \
            --cov-fail-under=50

   ##################### Build MCP Docker Image ########################
  build-mcp-docker:
    needs: security-and-quality  # Changed from publish-to-pypi
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-slim'
    permissions:
      contents: read
      packages: write
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for MCP server (GHCR only)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-mcp
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push MCP Docker image (to GHCR)
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/Dockerfile.mcp
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

   ##################### PyPI Publishing (DISABLED) ########################
  # publish-to-pypi:
  #   needs: security-and-quality
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   permissions:
  #     id-token: write  # Required for Trusted Publishing
  #     contents: read
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11'
  #         cache: 'pip'
  #
  #     - name: Install build dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install build
  #
  #     - name: Build package
  #       run: |
  #         echo "Building Python package..."
  #         python -m build
  #
  #     - name: Publish to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         print-hash: true
  #         skip-existing: true
  #         attestations: true  # Enable package attestations for better security

   ##################### Deployment ########################
  deploy:
    needs: [build-mcp-docker]  # Removed publish-to-pypi dependency
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-slim'
    steps:
      - name: MCP Docker Image Published
        id: deploy
        run: |
          echo "MCP Docker image published to GitHub Container Registry"
          echo "Image: ${{ needs.build-mcp-docker.outputs.image-tag }}"
          echo "Image Digest: ${{ needs.build-mcp-docker.outputs.image-digest }}"
          echo "Ready for deployment"
          echo ""
          echo "Pull command:"
          echo "docker pull ghcr.io/${{ github.repository }}-mcp:${{ github.ref_name }}"

      - name: Deployment Instructions
        run: |
          echo "🎉 MEMG Core (lean) build successful!"
          echo ""
          echo "🐳 MCP Server: docker pull ghcr.io/${{ github.repository }}-mcp:${{ github.ref_name }}"
          echo ""
          echo "🚀 Deploy MCP Server:"
          echo "1. docker pull ghcr.io/${{ github.repository }}-mcp:${{ github.ref_name }}"
          echo "2. cp env.example .env && edit GOOGLE_API_KEY"
          echo "3. docker run --env-file .env -p 8787:8787 ghcr.io/${{ github.repository }}-mcp:${{ github.ref_name }}"
          echo ""
          echo "📚 Core Library (PyPI publishing disabled for now):"
          echo "1. Local install: pip install -e ."
          echo "2. from memory_system.processing import MemoryRetriever"
