# .github/workflows/workflow.yml
name: MEMG Core – Main

on:
  push:
  workflow_dispatch:


env:
  full_sha: "${{ github.sha }}"
  branch_name: ${{ github.ref_name }}
  GIT_AUTHOR: ${{ github.event.head_commit.author.name }}
  GIT_COMMIT: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref_name }}
  GIT_REPO: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ################ building docker image ####################
  build_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        ############ checkout the code ######################
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Test ECR access
        run: |
          echo "Testing login to AWS ECR..."
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/z8i1z7l3

      - name: build docker image and push it gcr
        run: |
          ls -ll
          ls -R integrations
          docker build -t public.ecr.aws/z8i1z7l3/memg-core:${{env.branch_name}}-${{env.full_sha}} .
          docker push public.ecr.aws/z8i1z7l3/memg-core:${{env.branch_name}}-${{env.full_sha}}