name: create awesome workflow for memg core
on:
  push:


jobs:
  #################### Security & Quality Checks ########################
  #######################################################################
  security-and-quality-check:
    runs-on: ubuntu-latest
    steps:
      ############ checkout the code ##########
      - name: checkout the code
        uses: actions/checkout@v4


      ############# use python ################
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      ############# use bandit and ruff ################
      - name: use bandit (this is for security)
        run: |
          pip install -r requirements-dev.txt
          bandit -r src/ 
          







